apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80        # port inside cluster
      targetPort: 80  # container port
      nodePort: 30007 # port on Minikube VM
  type: NodePort